config/routes.rb
Rails.application.routes.draw do
  get 'inventory_item/index'

  resources :inventory_items
  resources :menu_items

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  validates :item_name, presence: true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_many :inventory_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  def index
    @inventory_items = InventoryItem.all
  end

  def edit
    @inventory_item = InventoryItem.find(params[:id])
  end

  def new
    @inventory_item = InventoryItem.new
  end

  def create
    @inventory_item = InventoryItem.new(inventory_item_params)

    if @inventory_item.save
      redirect_to @inventory_item
    else
      render 'new'
    end
  end

  def update
    @inventory_item = InventoryItem.find(params[:id])

    if @inventory_item.update(inventory_item_params)
      redirect_to @inventory_item
    else
      render 'edit'
    end
  end

  def show
    @inventory_item = InventoryItem.find(params[:id])
  end

  def destroy
    @inventory_item = InventoryItem.find(params[:id])
    @inventory_item.destroy

    redirect_to inventory_items_path
  end

  private
  def inventory_item_params
    params.require(:inventory_item).permit(:item_name, :amount_on_cart, :cost_per)
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @menu_items = MenuItem.all
  end

  def new
    @menu_item = MenuItem.new
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)

    if @menu_item.save
      redirect_to @menu_item
    else
      render 'new'
    end
  end

  def show
    @menu_item = MenuItem.find(params[:id])
  end

  private
  def menu_item_params
    params.require(:menu_item).permit(:product_name, :required_recipe_items, :recipe_item_amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<h1>Welcome</h1>
<%= link_to 'Inventory Index', inventory_items_path %>
<%= link_to 'New Inventory Item', new_inventory_item_path %>

app/views/inventory_item/new.html.erb
<h1>New Inventory Item</h1>
<%= form_with scope: :inventory_item, local: true do |form| %>
  <p>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </p>

  <!--<p>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </p> -->

  <p>
    <%= form.submit %>
    <%= link_to 'Back', inventory_item_index_path %>
  </p>
  <% end %>

app/views/inventory_items/_form.html.erb
<%= form_with model: @inventory_item, local: true, html: {novalidate: true} do |form| %>

  <% if @inventory_item.errors.any? %>
    <div id="error_explination">
      <h2>
        <%= pluralize(@inventory_item.errors.count, "error") %>
        prohibited this item from being saved
      </h2>
      <ul>
        <% @inventory_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :item_name %>
    <%= form.text_field :item_name %>
  </p>

  <p>
    <%= form.label :amount_on_cart %>
    <%= form.number_field :amount_on_cart %>
  </p>

  <p>
    <%= form.label :cost_per %>
    <%= form.number_field :cost_per %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/inventory_items/edit.html.erb
<h1>Edit Inventory Item</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/index.html.erb
<h1>Inventory Index</h1>
<table>
  <tr>
    <th>Inventory Item</th>
    <th>Amount On Cart</th>
    <th>Cost Per Item</th>
</tr>
  <% @inventory_items.each do |inventory_item| %>
    <tr>
      <td><%= inventory_item.item_name %></td>
      <td><%= inventory_item.amount_on_cart %></td>
      <td><%= inventory_item.cost_per %></td>
      <td><%= link_to 'show', inventory_item_path(inventory_item) %></td>
      <td><%= link_to 'edit', edit_inventory_item_path(inventory_item) %></td>
      <td><%= link_to 'Destroy', inventory_item_path(inventory_item),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Home', root_path %>
<%= link_to 'New Item', new_inventory_item_path %>

app/views/inventory_items/new.html.erb
<h1>New Inventory Item</h1>

<%= render 'form' %>

<%= link_to 'Back', inventory_items_path %>

app/views/inventory_items/show.html.erb
<p>
  <strong>Inventory Item</strong>
  <%= @inventory_item.item_name %>
</p>

<p>
  <strong>Amount On Cart</strong>
  <%= @inventory_item.amount_on_cart %>
</p>

<p>
  <strong>Cost Per oz</strong>
  <%= @inventory_item.cost_per %>
</p>

<%= link_to 'Home', root_path %>
<%= link_to 'Inventory Items', inventory_items_path %>
<%= link_to 'Edit', edit_inventory_item_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu_items/new.html.erb
<%= form_with scope: :menu_item, url: menu_items_path, local: true do |form| %>
  <p>
    <%= form.label :product_name %><br>
    <%= form.text_field :product_name %>
  </p>

  <% 5.times.each do %>
    <p>
      <%= form.label :required_recipe_items %><br>
      <%= form.collection_select :inventory_items, InventoryItem.order(:item_name), :id, :item_name, include_blank: true %>
    </p>

    <p>
      <%= form.label :recipe_item_amount %>
      <%= form.number_field :recipe_item_amount %>
    </p>
  <% end %>
<% end %>